function T = ZYZ(phi, theta, psi)
% ZYZ Euler homogeneous transformation matrix
% Input angles are in degrees
%
% T = Rot(z,phi) * Rot(y,theta) * Rot(z,psi)

    T = [ ...
        cosd(phi)*cosd(theta)*cosd(psi) - sind(phi)*sind(psi), ...
       -cosd(phi)*cosd(theta)*sind(psi) - sind(phi)*cosd(psi), ...
        cosd(phi)*sind(theta), ...
        0; ...
        
        sind(phi)*cosd(theta)*cosd(psi) + cosd(phi)*sind(psi), ...
       -sind(phi)*cosd(theta)*sind(psi) + cosd(phi)*cosd(psi), ...
        sind(phi)*sind(theta), ...
        0; ...
        
       -sind(theta)*cosd(psi), ...
        sind(theta)*sind(psi), ...
        cosd(theta), ...
        0; ...
        
        0, 0, 0, 1 ...
    ];
end